Fix broken test due to formatting error
cuducos/calculadora-do-cidadao pull request #45
Opened 2020-10-12 12:50 UTC by brunobcardoso

### What
The test `test_date_field_with_incomplete_dates` was failing due to Black format check.

### Details
```shell
.
.
.
tests/test_fields.py F..................                                                                                                                                     [ 94%]
tests/test_main.py s....                                                                                                                                                     [ 99%]
. .                                                                                                                                                                          [100%]

===================================================================================== FAILURES =====================================================================================
________________________________________________________________________________ Black format check ________________________________________________________________________________
--- /home/bruno/Development/calculadora-do-cidadao/tests/test_fields.py	2020-10-12 12:36:02.367622 +0000
+++ /home/bruno/Development/calculadora-do-cidadao/tests/test_fields.py	2020-10-12 12:36:19.619376 +0000
@@ -29,11 +29,18 @@
 def test_date_field_with_complete_dates(value):
     assert DateField.deserialize(value) == date(2018, 7, 6)
 
 
 @pytest.mark.parametrize(
-    "value", ("2018-07", "Jul/2018", "Jul-2018", "Jul 2018", "07/2018",),
+    "value",
+    (
+        "2018-07",
+        "Jul/2018",
+        "Jul-2018",
+        "Jul 2018",
+        "07/2018",
+    ),
 )
 def test_date_field_with_incomplete_dates(value):
     assert DateField.deserialize(value) == date(2018, 7, 1)
.
.
.
```

2020-10-12 12:58 UTC, cuducos commented
> The test `test_date_field_with_incomplete_dates` was failing due to Black format check.

I am afraid they weren't since [the CI is green](https://github.com/cuducos/calculadora-do-cidadao/actions/runs/212243031). Can you share more details about the environment so I can understand and replocate this here?

2020-10-12 20:42 UTC, brunobcardoso commented
> > The test `test_date_field_with_incomplete_dates` was failing due to Black format check.
> 
> I am afraid they weren't since [the CI is green](https://github.com/cuducos/calculadora-do-cidadao/actions/runs/212243031). Can you share more details about the environment so I can understand and replocate this here?

Sure! I've created a branch ([test-replication](https://github.com/brunobcardoso/calculadora-do-cidadao/commits/test-replication)) on my fork, removing the code climate from the workflow, just to replicate the error. 
https://github.com/brunobcardoso/calculadora-do-cidadao/runs/1244045111

But you could follow the steps below to replicate in your machine as well.

Environment:
- ubuntu latest
- pyenv with `3.7.9` and `3.8.6`

Steps:
Tox:
```shell
$ python -m venv .venv
$ source .venv/bin/activate
$ pip install --upgrade pip
$ pip install tox
$ tox
```
<details close>
<summary>Details</summary>

```shell
GLOB sdist-make: /calculadora-do-cidadao/setup.py
py37 create: /calculadora-do-cidadao/.tox/py37
py37 installdeps: -rrequirements-development.txt
py37 inst: /calculadora-do-cidadao/.tox/.tmp/package/1/calculadora-do-cidadao-0.5.0.zip
py37 installed: appdirs==1.4.4,attrs==20.2.0,black==20.8b1,calculadora-do-cidadao @ file:///calculadora-do-cidadao/.tox/.tmp/package/1/calculadora-do-cidadao-0.5.0.zip,certifi==2020.6.20,chardet==3.0.4,click==7.1.2,coverage==5.3,filelock==3.0.12,freezegun==1.0.0,idna==2.10,importlib-metadata==2.0.0,iniconfig==1.0.1,lxml==4.5.2,mypy==0.790,mypy-extensions==0.4.3,packaging==20.4,pathlib==1.0.1,pathspec==0.8.0,pluggy==0.13.1,py==1.9.0,pyparsing==2.4.7,pytest==6.1.1,pytest-black==0.3.12,pytest-cov==2.10.1,pytest-mock==3.3.1,pytest-mypy==0.7.0,python-dateutil==2.8.1,regex==2020.10.11,requests==2.24.0,rows==0.4.1,six==1.15.0,toml==0.10.1,typed-ast==1.4.1,typer==0.3.2,typing-extensions==3.7.4.3,unicodecsv==0.14.1,urllib3==1.25.10,xlrd==1.2.0,xlwt==1.3.0,zipp==3.3.0
py37 run-test-pre: PYTHONHASHSEED='2020844560'
py37 run-test: commands[0] | pytest
=========================================================== test session starts ============================================================
platform linux -- Python 3.7.9, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
cachedir: .tox/py37/.pytest_cache
rootdir: /calculadora-do-cidadao, configfile: setup.cfg
plugins: cov-2.10.1, mypy-0.7.0, black-0.3.12, mock-3.3.1
collected 111 items                                                                                                                        

setup.py ..                                                                                                                          [  1%]
calculadora_do_cidadao/__init__.py ..                                                                                                [  3%]
calculadora_do_cidadao/__main__.py ..                                                                                                [  5%]
calculadora_do_cidadao/download.py ..                                                                                                [  7%]
calculadora_do_cidadao/fields.py ..                                                                                                  [  8%]
calculadora_do_cidadao/months.py ..                                                                                                  [ 10%]
calculadora_do_cidadao/typing.py ..                                                                                                  [ 12%]
calculadora_do_cidadao/adapters/__init__.py ..                                                                                       [ 14%]
calculadora_do_cidadao/adapters/cpi.py ..                                                                                            [ 16%]
calculadora_do_cidadao/adapters/ibge.py ..                                                                                           [ 17%]
calculadora_do_cidadao/adapters/igpm.py ..                                                                                           [ 19%]
calculadora_do_cidadao/adapters/selic.py ..                                                                                          [ 21%]
docs/conf.py ..                                                                                                                      [ 23%]
tests/__init__.py ..                                                                                                                 [ 25%]
tests/conftest.py ..                                                                                                                 [ 26%]
tests/test_adapters.py ...........................................                                                                   [ 65%]
tests/test_base.py .......                                                                                                           [ 71%]
tests/test_download.py .......                                                                                                       [ 77%]
tests/test_fields.py F..................                                                                                             [ 94%]
tests/test_main.py .....                                                                                                             [ 99%]
. .                                                                                                                                  [100%]

================================================================= FAILURES =================================================================
____________________________________________________________ Black format check ____________________________________________________________
--- /calculadora-do-cidadao/tests/test_fields.py	2020-10-12 15:57:05.913634 +0000
+++ /calculadora-do-cidadao/tests/test_fields.py	2020-10-12 20:20:55.583658 +0000
@@ -29,11 +29,18 @@
 def test_date_field_with_complete_dates(value):
     assert DateField.deserialize(value) == date(2018, 7, 6)
 
 
 @pytest.mark.parametrize(
-    "value", ("2018-07", "Jul/2018", "Jul-2018", "Jul 2018", "07/2018",),
+    "value",
+    (
+        "2018-07",
+        "Jul/2018",
+        "Jul-2018",
+        "Jul 2018",
+        "07/2018",
+    ),
 )
 def test_date_field_with_incomplete_dates(value):
     assert DateField.deserialize(value) == date(2018, 7, 1)
 
 


----------- coverage: platform linux, python 3.7.9-final-0 -----------
Name                                          Stmts   Miss  Cover
-----------------------------------------------------------------
calculadora_do_cidadao/__init__.py                4      0   100%
calculadora_do_cidadao/__main__.py               25      0   100%
calculadora_do_cidadao/adapters/__init__.py      99      0   100%
calculadora_do_cidadao/adapters/cpi.py           14      0   100%
calculadora_do_cidadao/adapters/ibge.py          36      0   100%
calculadora_do_cidadao/adapters/igpm.py          21      0   100%
calculadora_do_cidadao/adapters/selic.py         21      0   100%
calculadora_do_cidadao/download.py               50      0   100%
calculadora_do_cidadao/fields.py                 30      0   100%
calculadora_do_cidadao/months.py                  5      0   100%
calculadora_do_cidadao/typing.py                  9      0   100%
-----------------------------------------------------------------
TOTAL                                           314      0   100%

=================================================================== mypy ===================================================================
Success: no issues found in 20 source files
========================================================= short test summary info ==========================================================
FAILED tests/test_fields.py::BLACK
============================================== 1 failed, 111 passed, 4476 warnings in 34.55s ===============================================
ERROR: InvocationError for command /calculadora [...]

2020-10-13 12:53 UTC, cuducos requested changes
Perfect, many many thanks… now I got it.

I see from [your logs](https://github.com/brunobcardoso/calculadora-do-cidadao/runs/1244045111#step:5:10) that this recent build is running with different versions of the dependencies (compared to the [two-months old one](https://github.com/brunobcardoso/calculadora-do-cidadao/runs/1244045111#step:5:10)) — more specifically, in this case, tests seam to be green when running with `black==19.10b0`, but red with `black==20.8b1`. Maybe newer versions of Black force a line break if sequences like tuples or lists end with a comma, but I haven't checked it. 

Your solution works, but I think it would be slighly better to just remove the trailing commas (since it's not a long line):

```python
@pytest.mark.parametrize(
    "value", ("2018-07", "Jul/2018", "Jul-2018", "Jul 2018", "07/2018")
)
```

This passes with new versions of Black. I'll leave that decision to you, I am going with whatever you think is better in terms of readability!

But, way more important than that: I think the _hotfix_ should include pinning `black` version to avoid differences like that, what do you think?

And, surely, beyond the _hotfix_ I think a better solution would be to embrace PEP 517 and use Poetry — I'll open an issue for that as this might be too much for the PR.

Many thanks!

2020-10-13 23:46 UTC, brunobcardoso commented
Wow! Way better than what I came up with. :) Thanks!

Good point regarding PEP 517. I saw there was #42 issue that might be duplicated with #46 somehow. But I can start working on it next week!

2020-10-14 13:05 UTC, merged

2020-10-14 13:05 UTC, cuducos commented
> I saw there was #42 issue that might be duplicated with #46 somehow.

Damn… that's true! I haven't seen that. Moving #46 contents then!

Many many thanks, buddy : )